channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - fermi::fermitools>=2.2.0
  # - astropy=6.1.1
  - astroquery==0.4.7
  - requests=2.32.3
  - tqdm==4.66.4
  - pip:
      - fermipy==1.3.1
  
